on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Jsonnet builder 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./
        id: Jsonnet
